services:
  - type: web
    name: tghsx-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SUPABASE_URL
        fromSecret: SUPABASE_URL
      - key: SUPABASE_KEY
        fromSecret: SUPABASE_KEY
      - key: WEB3_INFURA_PROJECT_ID
        fromSecret: WEB3_INFURA_PROJECT_ID
      - key: ADMIN_PRIVATE_KEY
        fromSecret: ADMIN_PRIVATE_KEY
      - key: COLLATERAL_VAULT_ADDRESS
        fromSecret: COLLATERAL_VAULT_ADDRESS
      - key: TGHSX_TOKEN_ADDRESS
        fromSecret: TGHSX_TOKEN_ADDRESS
      - key: PRICE_FEED_ADDRESS
        fromSecret: PRICE_FEED_ADDRESS
