services:
  - type: web
    name: tghs-backend
    runtime: python
    plan: free 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      # Blockchain Config
      - key: AMOY_RPC_URL
        fromGroup: tghs-env
      - key: LOCAL_RPC_URL
        fromGroup: tghs-env
      - key: PRIVATE_KEY
        fromGroup: tghs-env
      - key: POLYGONSCAN_API_KEY
        fromGroup: tghs-env
      
      # Contract Addresses
      - key: TGHSX_TOKEN_ADDRESS
        fromGroup: tghs-env
      - key: COLLATERAL_VAULT_ADDRESS
        fromGroup: tghs-env
      - key: MOCK_ETH_BTC_PRICE_FEED_ADDRESS
        fromGroup: tghs-env
      - key: MOCK_BTC_USD_PRICE_FEED_ADDRESS
        fromGroup: tghs-env
      - key: CHAINLINK_ETH_USD_PRICE_FEED_ADDRESS
        fromGroup: tghs-env
      - key: CHAINLINK_USD_GHS_PRICE_FEED_ADDRESS
        fromGroup: tghs-env
      
      # Minter Config
      - key: MINTER_ACCOUNT_ADDRESS
        fromGroup: tghs-env
      
      # Supabase Config
      - key: SUPABASE_URL
        fromGroup: tghs-env
      - key: SUPABASE_KEY
        fromGroup: tghs-env
      - key: SUPABASE_SERVICE_KEY
        fromGroup: tghs-env
      - key: ADMIN_USER_ID
        fromGroup: tghs-env
      - key: SUPABASE_JWT_SECRET
        fromGroup: tghs-env
      
      # Other Config
      - key: MIN_COLLATERAL_RATIO
        fromGroup: tghs-env
      - key: TELEGRAM_BOT_TOKEN
        fromGroup: tghs-env
      - key: TELEGRAM_CHAT_ID
        fromGroup: tghs-env